{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "nodes", "query": "node_cpu" },
   { "name": "mode", "label": "cpu mode", "query": "node_cpu" },
   { "name": "job", "label": "job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  { "title": "Gloal Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Document",
   "type": "text",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 1 },
   "content": "# Document\n\nThis is a custom dashboard Example, you can do everything you want to do with grafana's powerful visuial feature"
  },
  { "title": "Redirect To Other Dashboard", "type": "dashlist", "gridPos": { "h": 3, "w": 10, "x": 14, "y": 1 } },
  {
   "title": "Container Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_cpu_load_average_10s)",
     "legendFormat": "container count"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(node_load15)" }
   ]
  },
  {
   "title": "MEM Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_bytes_total) - sum(node_memory_free_bytes_total)) / sum(node_memory_bytes_total) * 100"
    }
   ]
  },
  {
   "title": "File System",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size) - sum(node_filesystem_avail)) / sum(node_filesystem_size) * 100"
    }
   ]
  },
  {
   "title": "$job State",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "repeat": "job",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(up{job=\"$job\"}) by (job)"
    }
   ]
  },
  {
   "title": "Prometheus Request Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_microseconds{instance=~\"$nodes\"} / 1000",
     "legendFormat": "{{instance}} {{ quantile }}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "nodes",
   "collapsed": true,
   "panels": [
    {
     "title": "Node Load 15m",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load15{instance=~\"$nodes\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node Cpu Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 16, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg (irate(node_cpu{mode=~'$mode', instance=~'$nodes'}[2m])) without (cpu)",
       "legendFormat": "{{instance}}-{{mode}}"
      }
     ]
    },
    {
     "title": "File System Usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(node_filesystem_size{instance=\"$nodes\"} - node_filesystem_avail{instance=\"$nodes\"}) by (instance) / sum(node_filesystem_size{instance=\"$nodes\"}) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}