{
 "title": "Prometheus Usage",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "$job health state",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "repeat": "job",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(up{job=\"$job\"}) by (job)"
    }
   ]
  },
  {
   "title": "Graph Counter Demo - CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (avg(irate(node_cpu{mode='idle'}[5m])) without (cpu))",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "Graph Summary Demo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_microseconds{quantile=\"0.99\"}",
     "legendFormat": "{{instance}} {{ handler }} 99"
    }
   ]
  },
  {
   "title": "Graph Gauge Example",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{ instance }} load1" }
   ]
  },
  {
   "title": "Graph Histogram Demo",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_compaction_duration_bucket",
     "legendFormat": "bucket-{{le}}"
    }
   ]
  },
  {
   "title": "Heatmap Histogram  Demo",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "prometheus_tsdb_compaction_duration_bucket",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Heatmap Gauge Sample",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "targets": [
    { "expr": "node_load1{}" }
   ]
  },
  {
   "title": "Single Stat Sample",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{instance=\"localhost:9100\"}"
    }
   ]
  },
  {
   "title": "Time series aggregations",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail{fstype=\"hfs\"}) without (job, mountpoint)",
     "legendFormat": "{{instance}}  {{ device }}"
    }
   ]
  },
  {
   "title": "Time series to column",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail) by (instance) / 1024",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "time series to row",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "node_filesystem_avail{instance=\"localhost:9100\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Table format",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "node_filesystem_avail{instance=\"localhost:9100\"}"
    }
   ]
  },
  {
   "title": "Annotation Table Sample",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {}
   ]
  }
 ]
}